# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "What is Eclipse Keyple"
  url = "#demo"
  weight = 10

[[main]]
  name = "Use cases"
  url = "#accomplishments"
  weight = 20

[[main]]
  name = "Blog"
  url = "#posts"
  weight = 30

[[main]]
  name = "Documentation"
  url = "docs/"
  weight = 40


[[main]]
  name = "Support"
  url = "#contact"
  weight = 50
